---
services:
  - docker

before_install:
  - sudo apt-get -qq update
  - docker pull store/citrix/netscalercpx:12.0-56.20
  - docker run -e EULA=yes -dt -p 22 -p 80 -p 161/udp --ulimit core=-1 --cap-add=NET_ADMIN store/citrix/netscalercpx:12.0-56.20

install:
  - sudo apt-get install -y sshpass cpanminus libwww-perl liblwp-protocol-https-perl libjson-perl
  - sudo cpanm Monitoring::Plugin

script: tests/travis_test.sh
